### PR TITLE
chore: v0.19 relnotes

### PR DESCRIPTION
**Pull request by wass3rw3rk**
script is kinda wip for now, but should be helpful at this point even. currently assumes a new full release tag has been cut on each repo.

will wait for some of the doc PRs to get merged to cross reference.

### CODE REVIEW

**Comment by ecrupper** [comment]
Script is really cool. Should we note the option to use worker registration in the release notes? Perhaps point to updated installation docs?

**Review by timhuynh94 — DISMISSED** [review]

**Comment by KellyMerrick** [comment]
Excited about this script! Should we remove the bots from the contributors?

**Comment by wass3rw3rk** [comment]
@ecrupper good call. i will cross reference when docs are merged

@KellyMerrick i'm cool with it. i'll add something that adds a section to note that there were dependency updates maybe when one of the bots shows up?

**Comment by wass3rw3rk** [comment]
i think i addressed both.. script is edited but still needs tweaks, so view as WIP. focus is release notes themselves.

**Review by ecrupper — APPROVED** [review]

**Review by KellyMerrick — APPROVED** [review]
lgtm

**Pull request merged**
