### PR TITLE
enhance(releases): add links for v0.8.0 release notes

### PR DESCRIPTION
**Pull request by jbrockopp**
Addressing feedback from https://github.com/go-vela/community/pull/276#issuecomment-853360888

cc: @JordanSussman

### CODE REVIEW

**Comment by JordanSussman** [comment]
I'm thinking it may be more clear if you link to the GitHub issue (assuming it exists) since that should have all the context and associated pull requests linked. Thoughts?

**Comment by jbrockopp** [comment]
> I'm thinking it may be more clear if you link to the GitHub issue (assuming it exists) since that should have all the context and associated pull requests linked. Thoughts?

Yeah I could certainly do that for the issues that were created 👍 

However, how do we handle the functionality that don't have a corresponding issue?

I think it get's tricky because all the documented changes will have a PR that can be linked.

Unfortunately, this doesn't hold true for all documented changes having an issue that can be linked.

To provide one example, adding HTML input sanitization:

https://github.com/go-vela/types/pull/166

**Comment by JordanSussman** [comment]
> However, how do we handle the functionality that doesn't have a corresponding issue?

Linking to the pull request(s) if no issue exists sound like a good middle ground.

**Comment by jbrockopp** [comment]
@JordanSussman I believe I have addressed your feedback 👍 

Also, I decided to try and be a bit more descriptive with the PR hyperlinks.

Please let me know your thoughts!

**Comment by JordanSussman** [comment]
LGTM! My only remaining feedback is to consider having all of the 0.8.x release notes within the same file instead of separating them out. I'm thinking of the same format as what https://github.com/hashicorp/terraform/blob/v0.15/CHANGELOG.md does.

**Comment by jbrockopp** [comment]
@JordanSussman I've discussed it with the team and there is interest in condensing the release notes like that 🎉 

You can expect that to be completed in a subsequent PR.

**Review by JordanSussman — APPROVED** [review]

**Review by KellyMerrick — APPROVED** [review]
lgtm

**Comment by jbrockopp** [comment]
> LGTM! My only remaining feedback is to consider having all of the 0.8.x release notes within the same file instead of separating them out. I'm thinking of the same format as what https://github.com/hashicorp/terraform/blob/v0.15/CHANGELOG.md does.

@JordanSussman this should be complete! 🎉

**Pull request merged**
