### PR TITLE
feat(proposal): repo allowed events remodel

### PR DESCRIPTION
**Pull request by ecrupper**

### CODE REVIEW

**Comment by cognifloyd** [comment]
I really like the bit masking option, but that also has another con (or 2, depending on how you count):
- Reordering entries or inserting entries will have to be prohibited
- Or we will have to add some kind of version byte at the beginning and either (a) migrate the field between updates, or (b) keep the older versions in the code so that we remain backwards compatibility.

I guess this falls under the "complexity" con.

**Comment by cognifloyd** [comment]
Option 3: Use a `JSON` column to store the JSON structure natively in postgres and sqlite. The `github.com/go-gorm/datatypes` package provides a type for this:
https://github.com/go-gorm/datatypes#json

**Review by plyr4 — APPROVED** [review]
@ecrupper is this good to merge in?

**Review by KellyMerrick — APPROVED** [review]
lgtm

**Review by timhuynh94 — APPROVED** [review]

**Pull request merged**
